### ISSUE TITLE
golangci-lint installation info need to be updated

### ISSUE THREAD

**Issue by gaolitao** [Wind-River/cloud-platform-deployment-manager#105]
https://install.goreleaser.com/github.com/golangci/golangci-lint.sh is not valid any more.

Need to update the DEVELOPER.md and [Dockerfile.builder](https://github.com/Wind-River/cloud-platform-deployment-manager/blob/master/Dockerfile.builder) which refer it.

https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh can be a candidate.

**Comment by yjian118** [comment]
With PR#123, this issue should be closed
